### ISSUE TITLE
dialog实现loading并不完美

### ISSUE THREAD

**Issue by liunewshine** [dengyuhan/LoadingBar#4]
dialog的坏处是会遮盖整个屏幕，造成所有操作无响应。
比如网络不好，超时时间是20s，用户必须等待20s，否则无法执行其他操作。或者出错后无法回调，造成dialog永远无法消失。用户必须结束app。
当然可以设置按实体返回键关闭dialog，但是这样会造成重复提交等很多问题
ios上面的loading不会遮住toolbar，只会遮住toolbar以下的页面，即使loading不消失，依然可以点击左上角的返回键。 android上面有办法实现吗？

**Comment by dengyuhan** [comment]
这个库默认的设置是，加载类的请求用LoadingBar，提交类的请求用LoadingDialog并且是不可取消的，一般做请求操作都会设超时时间，并且也会有取消请求的操作

你说的需求应该是用LoadingBar，不是LoadingDialog，只不过把LoadingView做成了像那个样子
