### ISSUE TITLE
LoadingBar 在 Fragment怎么用

### ISSUE THREAD

**Issue by qingchen1016** [dengyuhan/LoadingBar#6]
我这样获取parent 对吗？
private View mParent;
mParent = inflater.inflate(R.layout.fragment_monitor, null);

懒加载页面方法里LoadingBar.make(mParent).show();

获取数据成功的回调方法里   LoadingBar.cancel(mParent);

然而loadingbar出不来  
这是什么问题呢   
感谢

**Comment by dengyuhan** [comment]
parent必须是可覆盖的布局,比如RelativeLayout、FrameLayout

**Comment by qingchen1016** [comment]
感谢回复
