### ISSUE TITLE
使用自定义DialogFactory显示不出来?

### ISSUE THREAD

**Issue by dengzhiguiios** [dengyuhan/LoadingBar#8]
使用自定义DialogFactory显示不出来?
断点发现好像是使用自定义DialogFactory的时候isValid()方法不通过,
我传的上下文就是activity的,但是显示不出来?

**Comment by dengyuhan** [comment]
贴下代码，isValid()里面断点看到的context最终是activity吗

**Comment by dengzhiguiios** [comment]
LoadingDialog.make(this, new DialogFactory() {
            @Override
            public Dialog onCreateDialog(Context context) {
                View view = LayoutInflater.from(context).inflate(R.layout.layout_process_dialog, null);
                AlertDialog dialog = new AlertDialog.Builder(context, R.style.LoadingDialog)
                        .setView(view)
                        .setCancelable(false)
                        .create();
                //允许点返回键退出dialog
                dialog.setOnKeyListener(new DialogInterface.OnKeyListener() {
                    @Override
                    public boolean onKey(DialogInterface dialog, int keyCode, KeyEvent event) {
                        if (keyCode == KeyEvent.KEYCODE_BACK) {
                            dialog.dismiss();
                        }
                        return false;
                    }
                });
                return dialog;
            }

            @Override
            public void setMessage(Dialog dialog, CharSequence message) {
            }

            @Override
            public int getAnimateStyleId() {
                return 0;
            }
        }).show();

**Comment by dengzhiguiios** [comment]
isValid()方法里面的if (context instanceof Activity) {}没有进去,
说明context不是activity,
可是LoadingDialog的isValid()方法里面的上下文是通过dialog获取的:
Context context = mDialog.getContext();
而不是直接用LoadingDialog.make(this, new DialogFactory()).show();的this

**Comment by dengzhiguiios** [comment]
`XLog.e("is activity:" + (context instanceof Activity));
                View view = LayoutInflater.from(context).inflate(R.layout.layout_process_dialog, null);
                AlertDialog dialog = new AlertDialog.Builder(context, R.style.LoadingDialog)
                        .setView(view)
                        .setCancelable(false)
                        .create();
                //允许点返回键退出dialog
                dialog.setOnKeyListener(new DialogInterface.OnKeyListener() {
                    @Override
                    public boolean onKey(DialogInterface dialog, int keyCode, KeyEvent event) {
                        if (keyCode == KeyEvent.KEYCODE_BACK) {
                            dialog.dismiss();
                        }
                        return false;
                    }
                });
                XLog.e("is activity:" + (dialog.getContext() instanceof Activity));`
打印结果:
is activity:true
is activity:false
测试了一下直接从dialog获取的context不会是activity

**Comment by dengyuhan** [comment]
升级下1.4.9
```
implementation 'com.dyhdyh.loadingbar:loadingbar:1.4.9'
```

**Comment by dengzhiguiios** [comment]
谢谢,更新后已解决
